import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'

import Link from '@mui/material/Link';
import SvgIcon from '@mui/material/SvgIcon';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { css, jsx } from '@emotion/react'


const Home: NextPage = () => {
    const color = 'white'
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography sx={{ mt: 16, mb: 3,color:"red" }} color="text.secondary">
      Pro tip: See more  on
      the MUI documentation.
    </Typography>
      <main className={styles.main}>
          <Button variant="contained">Hello World</Button>
          1111
      </main>

      <footer className={styles.footer}>
          2222
      </footer>
    </div>
  )
}

export default Home
